name: Hello World
description: TikTuk Challenge
version: 0.1.0
appVersion: "1.0" 

image:
  repository: carlospleon/hello-tik-tuk-world
  tag: latest
  pullPolicy: IfNotPresent


service:
  enabled: true
  type: LoadBalancer
  port: 80
  targetPort: 8080

replicaCount: 1

resources: {}
  
nodeSelector: {}

tolerations: []

affinity: {}